[package]
name = "scylla"
version = "0.0.1"
edition = "2018"
description = "Async CQL driver for Rust, optimized for Scylla."
repository = "https://github.com/psarna/scylla-rust-driver"
readme = "../README.md"
keywords = ["database", "scylla", "cql"]
categories = ["database"]

[dependencies]
scylla-macros = { version = "0.1.0", path = "../scylla-macros"}
byteorder = "1.3.4"
bytes = "0.6.0"
futures = "0.3.6"
num_enum = "0.5"
compress = "0.2.1"
tokio = { version = "0.3.0", features = ["net", "time", "io-util", "sync", "rt", "macros"] }
snappy = "0.4.0"
uuid = "0.8.1"
rand = "0.7.3"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
