[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
anyhow = "1.0.33"
scylla = { path = "../scylla" }
futures = "0.3.6"
tokio = { version = "0.3.0", features = ["full"] }
rustyline = "6.3.0"

[[example]]
name = "basic"
path = "basic.rs"

[[example]]
name = "cqlsh-rs"
path = "cqlsh-rs.rs"

[[example]]
name = "parallel"
path = "parallel.rs"
